name: Run Jest Testes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧪 Rodar os testes com Jest
        run: npm test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: 📂 Upload das evidências de teste
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage
      - name: Enviar notificação para Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "🚀 Teste concluído com sucesso no GitHub Actions!"}' \
          $DISCORD_WEBHOOK