name: Run Jest Testes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Registrar horário de início
        run: echo "START_TIME=$(date +%s)" >> $GITHUB_ENV
        
      - name: 🚀 Checkout do repositório
        uses: actions/checkout@v4

      - name: 🔧 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🧪 Rodar os testes com Jest
        run: npm test
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

      - name: 📂 Upload das evidências de teste
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: coverage

      - name: Calcular duração dos testes
        run: |
          END_TIME=$(date +%s)
          DURATION=$((END_TIME - START_TIME))
          echo "DURATION=$DURATION" >> $GITHUB_ENV

      - name: Enviar notificação para Discord
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          JOB_NAME: "Test Execution"
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "username": "GitHub Actions",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "content": "**🚀 Teste Concluído!**\n
            📝 **Nome do Teste:** '"$JOB_NAME"'\n
            ⏱ **Duração:** '"$DURATION"' segundos\n
            🔗 [Veja no GitHub]('"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"')"
          }' \
          $DISCORD_WEBHOOK